### ISSUE TITLE
Peer Dependency

### ISSUE THREAD

**Issue by weihsth** [wlsf82/protractor-helper#1]
Hi!

I have the problem, that I use protractor AND protractor-helper as dependencies. npm 3+ is not installing protractor, because it's peer dependency from protractor-helper.

Only working solutions:
- installing protractor globally or particular (no way for me)
- copy your index file after each module update and paste it to my own module (works but it's just a 'hack')

Can it be removed as peer dependency? Everbody knows that it's needed.

**Comment by wlsf82** [comment]
Hi @weihsth, which version of Protractor do you have in the project where you're facing the issue.
I dislike the idea of removing the peer dependency, since this is the only way to ensure a warning will be shown in case Protractor is not installed.
I also noticed you mentioned npm v3+. Have you considered using a newer version?

**Comment by weihsth** [comment]
Hi @wlsf82, I use the protractor 5.1.1 at the moment.
Jea you are correct. It's good to have it. I don't know what the problem was. Since today it works...
Thank you for the reply!

**Comment by wlsf82** [comment]
Good to know that it is working. Let me know if you face it again.
