### ISSUE TITLE
Should we list the index.js file in the files property of the package.json

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#121]
@PauloGoncalvesBH, should we list the [`index.js`](https://github.com/wlsf82/protractor-helper/blob/master/index.js) in the [`files`](https://github.com/wlsf82/protractor-helper/blob/master/package.json#L32) property of the `package.json` file?

**Comment by wlsf82** [comment]
Or is it not needed because it's already the [`main`](https://github.com/wlsf82/protractor-helper/blob/master/package.json#L14) file?

**Comment by PauloGoncalvesBH** [comment]
It is not necessary. Since it is the 'main', it is automatically included in the final artifact. Putting in 'files' will only be to know explicitly what is going to the NPM after publishing.
You can test by running the 'npm pack' command and see the list of files that has been included. You will see that the 'index.js' will be listed.
