### ISSUE TITLE
Consider removing unit tests for the message builder

### ISSUE THREAD

**Issue by wlsf82** [wlsf82/protractor-helper#72]
There's no much sense in testing getters, which is basically what the [message builder tests](https://github.com/wlsf82/protractor-helper/blob/master/test/spec/messageBuilder.spec.js) are doing, and so it would be better to remove them all, which would reduce the codebase and also remove unnecessary complexity.

@PauloGoncalvesBH, what do you think?

**Comment by PauloGoncalvesBH** [comment]
I find it interesting to leave these tests as they are the only way to guarantee the correct functioning of the messaging functions.
If someone changes the directory, text or method name, the test will detect this.
About reducing codebase, I don't think that this point should be considered because the tests are not part of the artifact generated in the publication, withdrawing will not affect the package size.
